"""add_provider_availability_time_and_blackout_days

Revision ID: 073482a43e96
Revises: bd794137a8ce
Create Date: 2026-09-24 15:05:54.410882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '073482a43e96'
down_revision: Union[str, Sequence[str], None] = 'bd794137a8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('availability_time', sa.String(length=100), nullable=True))
    op.add_column('providers', sa.Column('blackout_days', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'blackout_days')
    op.drop_column('providers', 'availability_time')
    # ### end Alembic commands ###
