"""created new models

Revision ID: b5bcaeccf96f
Revises: c3d4e5f6a7b8
Create Date: 2026-09-04 12:16:22.767811

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b5bcaeccf96f'
down_revision: str | Sequence[str] | None = 'c3d4e5f6a7b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'service_id', name='uq_provider_service')
    )
    op.drop_index(op.f('ix_appointment_cancellations_appointment_id'), table_name='appointment_cancellations')
    op.drop_index(op.f('ix_appointment_cancellations_cancelled_at'), table_name='appointment_cancellations')
    op.drop_index(op.f('ix_notifications_appointment_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_appointment_id'), 'notifications', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_cancellations_cancelled_at'), 'appointment_cancellations', ['cancelled_at'], unique=False)
    op.create_index(op.f('ix_appointment_cancellations_appointment_id'), 'appointment_cancellations', ['appointment_id'], unique=False)
    op.drop_table('provider_services')
    # ### end Alembic commands ###
