"""Update Provider model

Revision ID: bd794137a8ce
Revises: ec3939c417ee
Create Date: 2026-09-24 11:25:28.367548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd794137a8ce'
down_revision: Union[str, Sequence[str], None] = 'ec3939c417ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('photo', sa.String(length=500), nullable=True))
    op.add_column('providers', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('providers', sa.Column('specializations', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True))
    op.add_column('providers', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'providers', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'providers', type_='foreignkey')
    op.drop_column('providers', 'user_id')
    op.drop_column('providers', 'specializations')
    op.drop_column('providers', 'bio')
    op.drop_column('providers', 'photo')
    # ### end Alembic commands ###
