"""add password reset otps

Revision ID: ec3939c417ee
Revises: d0e1f2a3b4c5
Create Date: 2026-09-23 11:45:13.431995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3939c417ee'
down_revision: Union[str, Sequence[str], None] = 'd0e1f2a3b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_otps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_reset_otps_user_used_created', 'password_reset_otps', ['user_id', 'used', 'created_at'], unique=False)
    op.drop_constraint(op.f('customers_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_customers_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_customers_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('customers_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_password_reset_otps_user_used_created', table_name='password_reset_otps')
    op.drop_table('password_reset_otps')
    # ### end Alembic commands ###
